name: CI-CD Todo App

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2

    

    # ðŸŸ¢ Backend Image
    - name: Build & Push Backend
      run: |
        docker build \
          -f backend/Dockerfile \
          -t todo-backend \
          backend

        docker tag todo-backend:latest ${{ secrets.ECR_REGISTRY }}/todo-backend:latest
        docker push ${{ secrets.ECR_REGISTRY }}/todo-backend:latest

    # ðŸŸ¢ Nginx Image
    - name: Build & Push Nginx
      run: |
        docker build \
          -f nginx/Dockerfile \
          -t todo-nginx \
          nginx

        docker tag todo-nginx:latest ${{ secrets.ECR_REGISTRY }}/todo-nginx:latest
        docker push ${{ secrets.ECR_REGISTRY }}/todo-nginx:latest

    # ðŸŸ¢ Deploy to EC2
    - name: Deploy on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker login -u AWS -p $(aws ecr get-login-password --region ap-south-1) ${{ secrets.ECR_REGISTRY }}

          docker pull ${{ secrets.ECR_REGISTRY }}/todo-backend:latest
          docker stop todo-backend || true
          docker rm todo-backend || true
          docker run -d \
            --name todo-backend \
            -p 3000:3000 \
            -e MONGODB_URL=${{ secrets.MONGO_URL }} \
            --restart unless-stopped \
            ${{ secrets.ECR_REGISTRY }}/todo-backend:latest

          docker pull ${{ secrets.ECR_REGISTRY }}/todo-nginx:latest
          docker stop todo-nginx || true
          docker rm todo-nginx || true
          docker run -d \
            --name todo-nginx \
            -p 80:80 \
            --restart unless-stopped \
            ${{ secrets.ECR_REGISTRY }}/todo-nginx:latest
